apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: my-project

  source:
    ### configuration to HELM Repo ###
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "*" # "*" to use the latest version

    ### configuration to reach GIT Repo with a HELM Chart inside, within GitHub ###
    # repoURL: https://github.com/prometheus-community/helm-charts.git
    # path: charts/kube-prometheus-stack
    # targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  # SYNC IS NOT ENABLED BY DEFAULT (it's a security mechanism to avoid accidental deletions)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true #it ensures that the namespace existes or get created

    automated:
      selfHeal: true #it ensures the app get exactly as defined in these files otherwise it syncs (creates what's missing)
      prune: true # and drop any external changes
