apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/moisesjurad0/argoCD-app-of-apps-definition
    path: app-root/apps # contains application spec files
    
    targetRevision: HEAD

  # SYNC IS NOT ENABLED BY DEFAULT (it's a security mechanism to avoid accidental deletions)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true #it ensures that the namespace existes or get created
    automated:
      selfHeal: true #it ensures the app get exactly as defined in these files otherwise it syncs (creates what's missing)
      prune: true # and drop any external changes
