apiVersion: v2
name: apph2
description: hi I'm a helm app project by m01
type: application
version: 1.0.0
# appVersion: "1.16.0"
dependencies:
  - name: kube-prometheus-stack
    # version: 0.0.3
    repository: https://prometheus-community.github.io/helm-charts/
